%YAML:1.0
---
SquareSpacing: 0.027
PatternType: 0
PatternSizeWidth: 7
PatternSizeHeight: 5
CalibrationVideo: "LifeCam_chess.webm"
CalibrationFile: "LifeCam_chess_calibration.yaml"
CalibrationFileRefined: "LifeCam_chess_calibration_refined.yaml"