%YAML:1.0
---
SquareSpacing: 0.035
PatternType: 2
PatternSizeWidth: 4
PatternSizeHeight: 11
CalibrationVideo: "LifeCam_asymmetric_circles.avi"
CalibrationFile: "LifeCam_asymmetric_circles_calibration"
CalibrationFileRefined: "LifeCam_asymmetric_circles_calibration_refined"