%YAML:1.0
---
SquareSpacing: 0.0443
PatternType: 3
PatternSizeWidth: 5
PatternSizeHeight: 4
CalibrationVideo: "PS3_rings.webm"
CalibrationFile: "PS3_rings_calibration.yaml"
CalibrationFileRefined: "PS3_rings_calibration_refined.yaml"